#!/usr/bin/perl

use strict;
use warnings;
use IO::Socket;

my $host = 'time.nist.gov';
my $port = 'daytime(13)';

my $sock = IO::Socket::INET->new(
        Proto       => 'tcp',
        PeerHost    => $host,
        PeerPort    => $port,
) or die "cannot connect: $!";

while (<$sock>) {
        s/^[[:space:]]+//;
        s/[[:space:]]+\z//s;
        next if /^$/;

        # NIST Daytime Protocol format
        # http://tf.nist.gov/service/its.htm
        # JJJJJ YR-MO-DA HH:MM:SS TT L H msADV UTC(NIST) OTM

        if ($_ =~ /^(\d+)\s+(\d{2})-(\d{2})-(\d{2})\s+(\d{2})\:(\d{2})\:(\d{2})/) {
                my($mjd, $yr, $mo, $dy, $hr, $mn, $sc) = ($1,$2,$3,$4,$5,$6,$7);
		my $settime = '20' . "$yr-$mo-$dy $hr:$mn:$sc" . '-0000';

                # adam 20050501 fix bug that sets time back to 1969
                if($yr != 69) {
                        #print "NIST: $yr-$mo-$dy $hr:$mn:$sc\n";
                        system("/bin/date -s '$settime'");

                } else {
                        #die("Time service not available today, try again tomorrow.");
                }

        } else {
                #print "$_\n";
        }
}
exit();
